name: Build

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  pull_request:
    branches-ignore:
      - '**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14, 16]

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Install pnpm
        run: npm install -g pnpm@6

      - name: Setup node
        uses: actions/setup-node@main
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm run eslint:lint

      - name: Build
        run: pnpm run build

      - name: Build API
        run: pnpm run build:api:dev

      - name: Test
        run: pnpm run test
