name: CI

on:
  push:
    branches-ignore: ['pr/**']
    tags: ['**']
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    container: node:16

    steps:
      - uses: actions/checkout@v2
      - run: npm install -g pnpm
      - run: pnpm install
      - run: pnpm run eslint:lint
      - run: pnpm run build
      - run: pnpm run test


  publish-npm:
    if: github.event_name == 'push' && github.ref_type == 'tag'
    runs-on: ubuntu-latest
    container: node:16-alpine
    needs: [test]

    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    steps:
      - uses: actions/checkout@v2
      - run: npm install -g pnpm
      - run: pnpm install
      - run: pnpm run build
      - run: pnpm config set "//registry.npmjs.org/:_authToken" "$NPM_TOKEN"
      - run: pnpm config set "git-tag-version" "false"
      - run: pnpm recursive exec npm version "${GITHUB_REF:11}"
      - run: pnpm recursive publish --access public --no-git-checks


  publish-docker:
    if: (github.event_name == 'push' && github.ref_type == 'tag') || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    needs: [test]

    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Release Tag
        if: ${{ github.event_name == 'push' && github.ref_type == 'tag' }}
        run: 'echo "TAG=${GITHUB_REF:11}" >> $GITHUB_ENV'

      - name: Canary Tag
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: 'echo "TAG=canary-${GITHUB_SHA:0:10}" >> $GITHUB_ENV'

      - name: Build & Publish Docker Image
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login --username "$DOCKER_USER" --password "$DOCKER_PASSWORD"
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --file ee/admin-server/Dockerfile \
            --cache-from type=registry,ref=ghcr.io/contember/admin \
            --cache-to   type=registry,ref=ghcr.io/contember/admin,mode=max \
            --tag "contember/admin:$TAG" \
            --push \
            .
